// বাংলাদেশের ৬৪টা জেলা, বিভাগ অনুযায়ী গোছানো
export const districts = [
  // Dhaka Division
  { en: 'Dhaka', bn: 'ঢাকা' },
  { en: 'Faridpur', bn: 'ফরিদপুর' },
  { en: 'Gazipur', bn: 'গাজীপুর' },
  { en: 'Gopalganj', bn: 'গোপালগঞ্জ' },
  { en: 'Kishoreganj', bn: 'কিশোরগঞ্জ' },
  { en: 'Madaripur', bn: 'মাদারীপুর' },
  { en: 'Manikganj', bn: 'মানিকগঞ্জ' },
  { en: 'Munshiganj', bn: 'মুন্সিগঞ্জ' },
  { en: 'Narayanganj', bn: 'নারায়ণগঞ্জ' },
  { en: 'Narsingdi', bn: 'নরসিংদী' },
  { en: 'Rajbari', bn: 'রাজবাড়ী' },
  { en: 'Shariatpur', bn: 'শরীয়তপুর' },
  { en: 'Tangail', bn: 'টাঙ্গাইল' },
  // Chattogram Division
  { en: 'Bandarban', bn: 'বান্দরবান' },
  { en: 'Brahmanbaria', bn: 'ব্রাহ্মণবাড়িয়া' },
  { en: 'Chandpur', bn: 'চাঁদপুর' },
  { en: 'Chattogram', bn: 'চট্টগ্রাম' },
  { en: 'Cumilla', bn: 'কুমিল্লা' },
  { en: "Cox's Bazar", bn: 'কক্সবাজার' },
  { en: 'Feni', bn: 'ফেনী' },
  { en: 'Khagrachari', bn: 'খাগড়াছড়ি' },
  { en: 'Lakshmipur', bn: 'লক্ষ্মীপুর' },
  { en: 'Noakhali', bn: 'নোয়াখালী' },
  { en: 'Rangamati', bn: 'রাঙ্গামাটি' },
  // Rajshahi Division
  { en: 'Bogura', bn: 'বগুড়া' },
  { en: 'Joypurhat', bn: 'জয়পুরহাট' },
  { en: 'Naogaon', bn: 'নওগাঁ' },
  { en: 'Natore', bn: 'নাটোর' },
  { en: 'Chapainawabganj', bn: 'চাঁপাইনবাবগঞ্জ' },
  { en: 'Pabna', bn: 'পাবনা' },
  { en: 'Rajshahi', bn: 'রাজশাহী' },
  { en: 'Sirajganj', bn: 'সিরাজগঞ্জ' },
  // Khulna Division
  { en: 'Bagerhat', bn: 'বাগেরহাট' },
  { en: 'Chuadanga', bn: 'চুয়াডাঙ্গা' },
  { en: 'Jashore', bn: 'যশোর' },
  { en: 'Jhenaidah', bn: 'ঝিনাইদহ' },
  { en: 'Khulna', bn: 'খুলনা' },
  { en: 'Kushtia', bn: 'কুষ্টিয়া' },
  { en: 'Magura', bn: 'মাগুরা' },
  { en: 'Meherpur', bn: 'মেহেরপুর' },
  { en: 'Narail', bn: 'নড়াইল' },
  { en: 'Satkhira', bn: 'সাতক্ষীরা' },
  // Barishal Division
  { en: 'Barguna', bn: 'বরগুনা' },
  { en: 'Barishal', bn: 'বরিশাল' },
  { en: 'Bhola', bn: 'ভোলা' },
  { en: 'Jhalokati', bn: 'ঝালকাঠি' },
  { en: 'Patuakhali', bn: 'পটুয়াখালী' },
  { en: 'Pirojpur', bn: 'পিরোজপুর' },
  // Sylhet Division
  { en: 'Habiganj', bn: 'হবিগঞ্জ' },
  { en: 'Moulvibazar', bn: 'মৌলভীবাজার' },
  { en: 'Sunamganj', bn: 'সুনামগঞ্জ' },
  { en: 'Sylhet', bn: 'সিলেট' },
  // Rangpur Division
  { en: 'Dinajpur', bn: 'দিনাজপুর' },
  { en: 'Gaibandha', bn: 'গাইবান্ধা' },
  { en: 'Kurigram', bn: 'কুড়িগ্রাম' },
  { en: 'Lalmonirhat', bn: 'লালমনিরহাট' },
  { en: 'Nilphamari', bn: 'নীলফামারী' },
  { en: 'Panchagarh', bn: 'পঞ্চগড়' },
  { en: 'Rangpur', bn: 'রংপুর' },
  { en: 'Thakurgaon', bn: 'ঠাকুরগাঁও' },
  // Mymensingh Division
  { en: 'Jamalpur', bn: 'জামালপুর' },
  { en: 'Mymensingh', bn: 'ময়মনসিংহ' },
  { en: 'Netrokona', bn: 'নেত্রকোণা' },
  { en: 'Sherpur', bn: 'শেরপুর' },
]